/**
 * Lessen: optellen tot 10 (naar Synthesis "Add within 10", groep 3 en 4).
 *
 * Het verloop volgt de lessen van Synthesis (INSPIRATIE.md, "Add within 10"):
 * eerst tegels leren kennen, dan op elkaar leggen en samen nemen, dan het veld
 * vol maken, omdraaien, dubbelen, kloppen sommen, het ontbrekende getal, drie
 * getallen en splitsen in meer delen. Een instaptoets en een eindtoets met
 * dezelfde soort vragen.
 */

import type { Les } from "@/lib/lessen/soort";
import { bolletjes, tegelsKiezen, tegelsKnoppen, tegelsTypen } from "@/lib/lessen/maak";

const ALLES = [1, 2, 3, 4, 5, 6, 7, 8, 9];
const KLOPT = ["klopt", "klopt niet"];

export const instaptoetsTot10: Les = {
  id: "tot10-instap",
  titel: "Instaptoets: optellen tot 10",
  synthesis: "Add within 10 · Assessment",
  stappen: [
    tegelsTypen({
      uitleg: ["Laat zien wat je al kunt.", "Dit is een tegel."],
      vraag: "Welk getal is deze tegel?",
      torens: [{ stukken: [3] }],
      antwoord: "3",
      goed: "Ja, dat is een 3.",
      fout: "Tel de gaatjes: het is een 3.",
      tip: "Elk gaatje is er één.",
    }),
    tegelsTypen({
      uitleg: ["Er komt een tegel bij."],
      vraag: "Wat is 3 en 4 samen?",
      kop: "3 + 4 = ?",
      torens: [{ stukken: [3, 4] }],
      antwoord: "7",
      goed: "3 en 4 is samen 7.",
      fout: "Tel ze samen: 3 en 4 is 7.",
      tip: "Tel alle gaatjes van de toren.",
    }),
    tegelsTypen({
      vraag: "Wat is 2 + 6?",
      kop: "2 + 6 = ?",
      torens: [{ stukken: [2, 6] }],
      antwoord: "8",
      goed: "2 en 6 is samen 8.",
      fout: "2 en 6 is samen 8.",
      tip: "Begin bij 6 en tel er 2 bij.",
    }),
    tegelsTypen({
      uitleg: ["Twee dezelfde tegels heet een dubbel."],
      vraag: "Wat is het dubbele van 3?",
      kop: "3 + 3 = ?",
      torens: [{ stukken: [3, 3] }],
      antwoord: "6",
      goed: "Het dubbele van 3 is 6.",
      fout: "3 en 3 is samen 6.",
      tip: "Tel 3 en nog eens 3.",
    }),
    tegelsTypen({
      vraag: "Wat is 7 + 8?",
      kop: "7 + 8 = ?",
      torens: [{ stukken: [7, 8] }],
      antwoord: "15",
      goed: "7 en 8 is samen 15.",
      fout: "7 en 3 is 10, en nog 5: 15.",
      tip: "Maak eerst de 10 vol.",
    }),
    tegelsKnoppen({
      uitleg: ["Links ligt 11, rechts 3 en 8."],
      vraag: "Klopt deze som?",
      kop: "3 + 8 = 11",
      torens: [{ stukken: [10, 1], getal: true }, { stukken: [3, 8], getal: true }],
      knoppen: KLOPT,
      antwoord: "klopt",
      goed: "Ja, even hoog: 3 + 8 is 11.",
      fout: "Kijk: ze zijn even hoog. 3 + 8 is 11.",
      tip: "Zijn de twee torens even hoog?",
    }),
    tegelsTypen({
      uitleg: ["De 4 ligt op de 10."],
      vraag: "Wat moet er bij 4 om 10 te maken?",
      kop: "4 + ? = 10",
      torens: [{ basis: 10, stukken: [4] }],
      antwoord: "6",
      goed: "4 en 6 maken samen 10.",
      fout: "Er blijven 6 gaatjes over: 4 en 6 is 10.",
      tip: "Tel wat er nog zichtbaar is van de 10.",
    }),
  ],
};

export const optellenOnder10: Les = {
  id: "tot10-onder10",
  titel: "Optellen onder de 10",
  synthesis: "Add within 10 · Adding below 10",
  stappen: [
    tegelsTypen({
      uitleg: ["Dit zijn tegels.", "Elke tegel heeft een eigen kleur."],
      vraag: "Welk getal is deze tegel?",
      torens: [{ stukken: [4] }],
      antwoord: "4",
      goed: "Ja, de limoen tegel is een 4.",
      fout: "Tel de gaatjes: het is een 4.",
      tip: "Tel de gaatjes.",
    }),
    tegelsTypen({
      uitleg: ["Nog een tegel."],
      vraag: "Welk getal is deze tegel?",
      torens: [{ stukken: [3] }],
      antwoord: "3",
      goed: "Ja, de gele tegel is een 3.",
      fout: "Tel de gaatjes: het is een 3.",
      tip: "Tel de gaatjes.",
    }),
    tegelsTypen({
      uitleg: ["Twee tegels op elkaar klikken vast.", "Samen worden ze één toren."],
      vraag: "Hoeveel zijn 2 en 3 samen?",
      kop: "2 + 3 = ?",
      torens: [{ stukken: [2, 3] }],
      antwoord: "5",
      goed: "2 en 3 is samen 5.",
      fout: "Tel alle gaatjes: 2 en 3 is 5.",
      tip: "Tel alle gaatjes van de toren.",
    }),
    tegelsTypen({
      uitleg: ["Kijk: de 3 past in de 5."],
      vraag: "Hoeveel zijn 3 en 5 samen?",
      kop: "3 + 5 = ?",
      torens: [{ stukken: [3, 5] }],
      antwoord: "8",
      goed: "3 en 5 is samen 8.",
      fout: "Iets meer dan 7: 3 en 5 is 8.",
      tip: "Begin bij 5 en tel er 3 bij.",
    }),
    tegelsKiezen({
      uitleg: ["Er ligt een 6.", "Het lege stuk moet vol."],
      vraag: "Welke tegel maakt samen met 6 precies 7?",
      kop: "6 + ? = 7",
      torens: [{ stukken: [6], gat: 7 }],
      bak: ALLES,
      antwoord: "1",
      goed: "6 en 1 maken samen 7.",
      fout: "Er moest nog 1 bij: 6 en 1 is 7.",
      tip: "Hoeveel lege gaatjes zie je?",
    }),
    tegelsKiezen({
      uitleg: ["We maken het moeilijker.", "Maak 10 met de 3."],
      vraag: "Welke tegel maakt samen met 3 precies 10?",
      kop: "3 + ? = 10",
      torens: [{ stukken: [3], gat: 10 }],
      bak: ALLES,
      antwoord: "7",
      goed: "3 en 7 maken samen 10.",
      fout: "Er moest nog 7 bij: 3 en 7 is 10.",
      tip: "Hoeveel lege gaatjes zie je?",
    }),
    tegelsKnoppen({
      uitleg: ["De 3 en de 7 zijn samen 10."],
      vraag: "Hoe schrijf je dit als som?",
      torens: [{ stukken: [3, 7] }],
      knoppen: ["3 + 7 = 10", "3 + 7 = 37", "3 − 7 = 10"],
      antwoord: "3 + 7 = 10",
      goed: "Ja: 3 + 7 = 10.",
      fout: "Het is plus, en samen 10: 3 + 7 = 10.",
      tip: "Komt er iets bij of gaat er iets af?",
    }),
    tegelsTypen({
      uitleg: ["De toren draait om.", "Nu ligt de 7 onderop."],
      vraag: "Wat is het totaal nu?",
      kop: "7 + 3 = ?",
      torens: [{ stukken: [7, 3] }],
      antwoord: "10",
      goed: "Nog steeds 10: omdraaien maakt niet uit.",
      fout: "Het blijft 10: 7 + 3 is evenveel als 3 + 7.",
      tip: "Er komt niets bij en er gaat niets af.",
    }),
    tegelsKiezen({
      uitleg: ["De 3 en de 7 zijn op.", "Zoek een andere manier om 10 te maken."],
      vraag: "Welke tegel maakt samen met 4 precies 10?",
      kop: "4 + ? = 10",
      torens: [{ stukken: [4], gat: 10 }],
      bak: [1, 2, 4, 5, 6, 8, 9],
      antwoord: "6",
      goed: "4 en 6 maken samen 10.",
      fout: "Er moest nog 6 bij: 4 en 6 is 10.",
      tip: "Hoeveel lege gaatjes zie je?",
    }),
  ],
};

export const dubbelen: Les = {
  id: "tot10-dubbelen",
  titel: "Dubbelen",
  synthesis: "Add within 10 · Doubles",
  stappen: [
    tegelsTypen({
      uitleg: ["Twee dezelfde tegels heet een dubbel.", "Hier liggen twee keer 3."],
      vraag: "Wat is het dubbele van 3?",
      kop: "3 + 3 = ?",
      torens: [{ stukken: [3, 3] }],
      antwoord: "6",
      goed: "Het dubbele van 3 is 6.",
      fout: "Net niet: 3 en 3 is samen 6.",
      tip: "Tel 3 en 3 samen.",
    }),
    tegelsKnoppen({
      uitleg: ["Kijk naar de vorm.", "Twee keer 3 lijkt op de 6."],
      vraag: "Zijn de torens even hoog?",
      torens: [{ stukken: [3, 3], getal: true }, { stukken: [6], getal: true }],
      knoppen: ["ja", "nee"],
      antwoord: "ja",
      goed: "Ja: 3 + 3 is precies 6.",
      fout: "Ze zijn even hoog: 3 + 3 is 6.",
      tip: "Kijk of er een gaatje uitsteekt.",
    }),
    tegelsTypen({
      uitleg: ["Nog een dubbel: twee keer 4."],
      vraag: "Wat is het dubbele van 4?",
      kop: "4 + 4 = ?",
      torens: [{ stukken: [4, 4] }],
      antwoord: "8",
      goed: "Het dubbele van 4 is 8.",
      fout: "4 en 4 is samen 8.",
      tip: "Tel 4 en 4 samen.",
    }),
    tegelsTypen({
      vraag: "Wat is het dubbele van 2?",
      kop: "2 + 2 = ?",
      torens: [{ stukken: [2, 2] }],
      antwoord: "4",
      goed: "Het dubbele van 2 is 4.",
      fout: "2 en 2 is samen 4.",
      tip: "Tel 2 en 2 samen.",
    }),
    tegelsTypen({
      vraag: "Wat is het dubbele van 5?",
      kop: "5 + 5 = ?",
      torens: [{ stukken: [5, 5] }],
      antwoord: "10",
      goed: "Het dubbele van 5 is 10.",
      fout: "5 en 5 is samen 10.",
      tip: "Tel 5 en 5 samen.",
    }),
    tegelsKiezen({
      uitleg: ["Nu andersom.", "Hier ligt een 4.", "Leg er een tegel op."],
      vraag: "Welk getal moet je verdubbelen om 4 te maken?",
      torens: [{ basis: 4 }],
      bak: [1, 2, 3],
      antwoord: "2",
      goed: "Ja: 2 en nog eens 2 is 4.",
      fout: "De 2 bedekt de helft: 2 en 2 is 4.",
      tip: "Leg een tegel op de helft.",
    }),
    tegelsKiezen({
      uitleg: ["Hier ligt een 8."],
      vraag: "Welk getal moet je verdubbelen om 8 te maken?",
      torens: [{ basis: 8 }],
      bak: [2, 3, 4, 5],
      antwoord: "4",
      goed: "Ja: 4 en nog eens 4 is 8.",
      fout: "De 4 bedekt de helft: 4 en 4 is 8.",
      tip: "Leg een tegel op de helft.",
    }),
    tegelsKiezen({
      uitleg: ["Hier ligt een 10."],
      vraag: "Welk getal moet je verdubbelen om 10 te maken?",
      torens: [{ basis: 10 }],
      bak: [3, 4, 5, 6],
      antwoord: "5",
      goed: "Ja: 5 en nog eens 5 is 10.",
      fout: "De 5 bedekt de helft: 5 en 5 is 10.",
      tip: "Leg een tegel op de helft.",
    }),
  ],
};

export const kloptDeSom: Les = {
  id: "tot10-klopt",
  titel: "Klopt de som?",
  synthesis: "Add within 10 · True or False",
  stappen: [
    tegelsKnoppen({
      uitleg: ["Een som klopt als beide kanten even veel zijn.", "Links de 6, rechts 3 en 2."],
      vraag: "Klopt deze som?",
      kop: "3 + 2 = 6",
      torens: [{ stukken: [6], getal: true }, { stukken: [3, 2], getal: true }],
      knoppen: KLOPT,
      antwoord: "klopt niet",
      goed: "Goed gezien: 3 + 2 is 5, niet 6.",
      fout: "Kijk: er mist een gaatje. 3 + 2 is 5.",
      tip: "Zijn de twee torens even hoog?",
    }),
    tegelsKiezen({
      uitleg: ["Maak hem kloppend.", "Leg er één tegel bij."],
      vraag: "Welke tegel maakt de torens even hoog?",
      kop: "3 + 2 + ? = 6",
      torens: [{ stukken: [6], getal: true }, { stukken: [3, 2], gat: 6 }],
      leg: 1,
      bak: [1, 2, 3],
      antwoord: "1",
      goed: "Zo klopt het: 3 + 2 + 1 = 6.",
      fout: "Er mist er 1: 3 + 2 + 1 = 6.",
      tip: "Hoeveel gaatjes mist de rechter toren?",
    }),
    tegelsKnoppen({
      uitleg: ["Links 11: een 10 en een 1."],
      vraag: "Klopt deze som?",
      kop: "5 + 6 = 11",
      torens: [{ stukken: [10, 1], getal: true }, { stukken: [5, 6], getal: true }],
      knoppen: KLOPT,
      antwoord: "klopt",
      goed: "Ja, even hoog: 5 + 6 is 11.",
      fout: "Ze zijn even hoog: 5 + 6 is 11.",
      tip: "Zijn de twee torens even hoog?",
    }),
    tegelsKnoppen({
      uitleg: ["Nu met drie getallen."],
      vraag: "Klopt deze som?",
      kop: "2 + 3 + 4 = 8",
      torens: [{ stukken: [8], getal: true }, { stukken: [2, 3, 4], getal: true }],
      knoppen: KLOPT,
      antwoord: "klopt niet",
      goed: "Goed gezien: 2 + 3 + 4 is 9.",
      fout: "Er steekt er 1 uit: 2 + 3 + 4 is 9.",
      tip: "Steekt er een gaatje uit?",
    }),
    tegelsKnoppen({
      uitleg: ["Nu zonder te tellen, als het lukt."],
      vraag: "Klopt deze som?",
      kop: "2 + 7 = 9",
      torens: [{ stukken: [9], getal: true }, { stukken: [2, 7], getal: true }],
      knoppen: KLOPT,
      antwoord: "klopt",
      goed: "Dat klopt: 2 + 7 = 9.",
      fout: "Ze zijn even hoog: 2 + 7 is 9.",
      tip: "Begin bij 7 en tel er 2 bij.",
    }),
    tegelsKnoppen({
      vraag: "Klopt deze som?",
      kop: "4 + 4 = 9",
      torens: [{ stukken: [9], getal: true }, { stukken: [4, 4], getal: true }],
      knoppen: KLOPT,
      antwoord: "klopt niet",
      goed: "Goed gezien: 4 + 4 is 8.",
      fout: "Er mist er 1: 4 + 4 is 8.",
      tip: "Wat is het dubbele van 4?",
    }),
    tegelsKnoppen({
      uitleg: ["Nu een moeilijke, met vier getallen."],
      vraag: "Klopt deze som?",
      kop: "1 + 2 + 3 + 4 = 10",
      torens: [{ stukken: [10], getal: true }, { stukken: [1, 2, 3, 4], getal: true }],
      knoppen: KLOPT,
      antwoord: "klopt",
      goed: "Dat klopt: 1 + 2 + 3 + 4 = 10.",
      fout: "Ze zijn even hoog: samen is het 10.",
      tip: "Tel eerst 1 + 2 + 3, dan de 4 erbij.",
    }),
  ],
};

export const ontbrekendGetal: Les = {
  id: "tot10-ontbrekend",
  titel: "Het ontbrekende getal",
  synthesis: "Add within 10 · Missing Numbers",
  stappen: [
    tegelsTypen({
      uitleg: ["Kijk naar deze blauwe tegel."],
      vraag: "Welk getal is deze tegel?",
      torens: [{ basis: 7 }],
      antwoord: "7",
      goed: "Ja, de blauwe tegel is een 7.",
      fout: "Tel de gaatjes: het is een 7.",
      tip: "Tel de gaatjes.",
    }),
    tegelsTypen({
      uitleg: ["De gele 3 ligt op de 7.", "Een stuk van de 7 blijft zichtbaar."],
      vraag: "Hoeveel blijft er over van de 7?",
      kop: "3 + ? = 7",
      torens: [{ basis: 7, stukken: [3] }],
      antwoord: "4",
      goed: "Ja: 3 en 4 maken samen 7.",
      fout: "Tel de blauwe gaatjes: het zijn er 4.",
      tip: "Tel alleen de blauwe gaatjes.",
    }),
    tegelsKiezen({
      uitleg: ["Er ligt een 5 op de 9."],
      vraag: "Welke tegel past precies op het blauwe stuk?",
      kop: "5 + ? = 9",
      torens: [{ basis: 9, stukken: [5] }],
      bak: [1, 2, 3, 4, 5, 6],
      antwoord: "4",
      goed: "Ja: 5 en 4 maken samen 9.",
      fout: "Er bleven 4 gaatjes over: 5 en 4 is 9.",
      tip: "Hoeveel gaatjes van de 9 zie je nog?",
    }),
    tegelsTypen({
      vraag: "Wat moet er bij 6 om 8 te maken?",
      kop: "6 + ? = 8",
      torens: [{ basis: 8, stukken: [6] }],
      antwoord: "2",
      goed: "Ja: 6 en 2 maken samen 8.",
      fout: "Er blijven 2 gaatjes over: 6 en 2 is 8.",
      tip: "Tel wat er nog zichtbaar is van de 8.",
    }),
    tegelsKiezen({
      uitleg: ["Je doet het goed.", "Nu een moeilijke, tot 11."],
      vraag: "Welke tegel maakt samen met 4 precies 11?",
      kop: "4 + ? = 11",
      torens: [{ stukken: [4], gat: 11 }],
      bak: [4, 5, 6, 7, 8],
      antwoord: "7",
      goed: "Ja: 4 en 7 maken samen 11.",
      fout: "Er moest nog 7 bij: 4 en 7 is 11.",
      tip: "Gebruik de tegels: hoeveel gaatjes zijn nog leeg?",
    }),
    tegelsTypen({
      vraag: "Wat moet er bij 3 om 10 te maken?",
      kop: "3 + ? = 10",
      torens: [{ basis: 10, stukken: [3] }],
      antwoord: "7",
      goed: "Ja: 3 en 7 maken samen 10.",
      fout: "Er blijven 7 gaatjes over: 3 en 7 is 10.",
      tip: "Tel wat er nog zichtbaar is van de 10.",
    }),
  ],
};

export const drieGetallen: Les = {
  id: "tot10-drie",
  titel: "Drie getallen optellen",
  synthesis: "Add within 10 · Add Three Numbers",
  stappen: [
    tegelsTypen({
      uitleg: ["Drie tegels op elkaar.", "Samen maken ze een staaf."],
      vraag: "Hoeveel is 2 + 7 + 1?",
      kop: "2 + 7 + 1 = ?",
      torens: [{ stukken: [2, 7, 1] }],
      antwoord: "10",
      goed: "2 + 7 + 1 is samen 10.",
      fout: "Tel alles samen: 2 + 7 + 1 is 10.",
      tip: "Eerst 2 en 7, dan nog 1.",
    }),
    tegelsKiezen({
      uitleg: ["Dit gat heeft de vorm van 9.", "Vul het met drie tegels."],
      vraag: "Welke drie tegels maken samen 9?",
      kop: "? + ? + ? = 9",
      torens: [{ gat: 9 }],
      bak: [1, 2, 3, 4, 5, 6],
      kies: 3,
      antwoord: "1,2,6|1,3,5|2,3,4",
      goed: "Ja, het gat is precies vol.",
      fout: "Bijvoorbeeld 2 + 3 + 4 is samen 9.",
      tip: "Kies er drie die samen 9 zijn.",
    }),
    tegelsKiezen({
      uitleg: ["Nu de vorm van 6."],
      vraag: "Welke drie tegels maken samen 6?",
      kop: "? + ? + ? = 6",
      torens: [{ gat: 6 }],
      bak: [1, 2, 3, 4],
      kies: 3,
      antwoord: "1,2,3",
      goed: "Helemaal goed: 1 + 2 + 3 = 6.",
      fout: "1 + 2 + 3 is samen 6.",
      tip: "Probeer de kleinste tegels.",
    }),
    tegelsKiezen({
      uitleg: ["En de vorm van 8."],
      vraag: "Welke drie tegels maken samen 8?",
      kop: "? + ? + ? = 8",
      torens: [{ gat: 8 }],
      bak: [1, 2, 3, 4, 5, 6],
      kies: 3,
      antwoord: "1,2,5|1,3,4",
      goed: "Ja, het gat is precies vol.",
      fout: "Bijvoorbeeld 1 + 3 + 4 is samen 8.",
      tip: "Kies er drie die samen 8 zijn.",
    }),
    tegelsTypen({
      vraag: "Hoeveel is 3 + 4 + 2?",
      kop: "3 + 4 + 2 = ?",
      torens: [{ stukken: [3, 4, 2] }],
      antwoord: "9",
      goed: "3 + 4 + 2 is samen 9.",
      fout: "3 en 4 is 7, en nog 2: 9.",
      tip: "Eerst 3 en 4, dan nog 2.",
    }),
    tegelsTypen({
      vraag: "Hoeveel is 5 + 1 + 4?",
      kop: "5 + 1 + 4 = ?",
      torens: [{ stukken: [5, 1, 4] }],
      antwoord: "10",
      goed: "5 + 1 + 4 is samen 10.",
      fout: "5 en 1 is 6, en nog 4: 10.",
      tip: "Eerst 5 en 1, dan nog 4.",
    }),
  ],
};

export const splitsenInDelen: Les = {
  id: "tot10-splitsen",
  titel: "Splitsen in meer delen",
  synthesis: "Add within 10 · Splitting Sums",
  stappen: [
    bolletjes({
      uitleg: ["Kijk naar dit groepje bolletjes."],
      vraag: "Hoeveel bolletjes zijn het?",
      invoer: "typen",
      groepen: [7],
      antwoord: "7",
      goed: "Ja, het zijn er 7.",
      fout: "Tel ze één voor één: het zijn er 7.",
      tip: "Tel ze één voor één.",
    }),
    bolletjes({
      uitleg: ["Het groepje valt uit elkaar in losse bolletjes.", "Elk bolletje is een 1."],
      vraag: "Hoeveel enen zijn het?",
      invoer: "typen",
      groepen: [1, 1, 1, 1, 1, 1, 1],
      antwoord: "7",
      goed: "Ja: zeven enen samen is 7.",
      fout: "Tel de enen: het zijn er 7.",
      tip: "Tel de enen.",
    }),
    bolletjes({
      uitleg: ["Nu maken we groepjes: 3, 3 en 1."],
      vraag: "Hoeveel is 3 + 3 + 1?",
      kop: "3 + 3 + 1 = ?",
      invoer: "typen",
      groepen: [3, 3, 1],
      antwoord: "7",
      goed: "Nog steeds 7: 3 + 3 + 1 = 7.",
      fout: "Het blijft 7: 3 + 3 + 1 = 7.",
      tip: "Er komt niets bij en er gaat niets af.",
    }),
    bolletjes({
      uitleg: ["Hier liggen 7 enen."],
      vraag: "Welke som kun je maken met 7?",
      invoer: "kiezen",
      groepen: [1, 1, 1, 1, 1, 1, 1],
      knoppen: ["2 + 1 + 2 + 1", "3 + 2 + 1 + 1", "1 + 3 + 2 + 2"],
      antwoord: "3 + 2 + 1 + 1",
      goed: "Ja: 3 + 2 + 1 + 1 is samen 7.",
      fout: "3 + 2 + 1 + 1 is 7. De andere zijn 6 en 8.",
      tip: "Tel elke som na.",
    }),
    bolletjes({
      uitleg: ["Nu 8 enen."],
      vraag: "Welke som kun je maken met 8?",
      invoer: "kiezen",
      groepen: [1, 1, 1, 1, 1, 1, 1, 1],
      knoppen: ["1 + 4 + 2 + 1", "2 + 2 + 2 + 3", "4 + 1 + 1 + 1"],
      antwoord: "1 + 4 + 2 + 1",
      goed: "Ja: 1 + 4 + 2 + 1 is samen 8.",
      fout: "1 + 4 + 2 + 1 is 8. De andere zijn 9 en 7.",
      tip: "Tel elke som na.",
    }),
    bolletjes({
      uitleg: ["Let op: nu andersom."],
      vraag: "Welke som kun je níet maken met 8?",
      invoer: "kiezen",
      groepen: [1, 1, 1, 1, 1, 1, 1, 1],
      knoppen: ["2 + 3 + 2 + 2", "4 + 2 + 1 + 1", "3 + 3 + 1 + 1"],
      antwoord: "2 + 3 + 2 + 2",
      goed: "Goed gezien: 2 + 3 + 2 + 2 is 9.",
      fout: "2 + 3 + 2 + 2 is 9. Dat is één te veel.",
      tip: "Welke som is geen 8?",
    }),
    bolletjes({
      uitleg: ["Nog één: 6 enen."],
      vraag: "Welke som kun je maken met 6?",
      invoer: "kiezen",
      groepen: [1, 1, 1, 1, 1, 1],
      knoppen: ["3 + 2 + 2", "2 + 2 + 2", "4 + 1 + 2"],
      antwoord: "2 + 2 + 2",
      goed: "Ja: 2 + 2 + 2 is samen 6.",
      fout: "2 + 2 + 2 is 6. De andere zijn allebei 7.",
      tip: "Tel elke som na.",
    }),
  ],
};

export const eindtoetsTot10: Les = {
  id: "tot10-eind",
  titel: "Eindtoets: optellen tot 10",
  synthesis: "Add within 10 · Mastery Check",
  stappen: [
    tegelsTypen({
      uitleg: ["Laat zien wat je nu kunt."],
      vraag: "Welk getal is deze tegel?",
      torens: [{ stukken: [6] }],
      antwoord: "6",
      goed: "Ja, de lichtblauwe tegel is een 6.",
      fout: "Tel de gaatjes: het is een 6.",
      tip: "Tel de gaatjes.",
    }),
    tegelsTypen({
      vraag: "Wat is 2 + 5?",
      kop: "2 + 5 = ?",
      torens: [{ stukken: [2, 5] }],
      antwoord: "7",
      goed: "2 en 5 is samen 7.",
      fout: "2 en 5 is samen 7.",
      tip: "Begin bij 5 en tel er 2 bij.",
    }),
    tegelsTypen({
      vraag: "Wat is het dubbele van 4?",
      kop: "4 + 4 = ?",
      torens: [{ stukken: [4, 4] }],
      antwoord: "8",
      goed: "Het dubbele van 4 is 8.",
      fout: "4 en 4 is samen 8.",
      tip: "Tel 4 en 4 samen.",
    }),
    tegelsTypen({
      vraag: "Wat is 6 + 7?",
      kop: "6 + 7 = ?",
      torens: [{ stukken: [6, 7] }],
      antwoord: "13",
      goed: "6 en 7 is samen 13.",
      fout: "6 en 4 is 10, en nog 3: 13.",
      tip: "Maak eerst de 10 vol.",
    }),
    tegelsKnoppen({
      vraag: "Klopt deze som?",
      kop: "7 + 2 = 10",
      torens: [{ stukken: [10], getal: true }, { stukken: [7, 2], getal: true }],
      knoppen: KLOPT,
      antwoord: "klopt niet",
      goed: "Goed gezien: 7 + 2 is 9.",
      fout: "Er mist er 1: 7 + 2 is 9.",
      tip: "Zijn de twee torens even hoog?",
    }),
    tegelsTypen({
      vraag: "Wat moet er bij 6 om 10 te maken?",
      kop: "6 + ? = 10",
      torens: [{ basis: 10, stukken: [6] }],
      antwoord: "4",
      goed: "6 en 4 maken samen 10.",
      fout: "Er blijven 4 gaatjes over: 6 en 4 is 10.",
      tip: "Tel wat er nog zichtbaar is van de 10.",
    }),
  ],
};

export const LESSEN_TOT10: Les[] = [
  instaptoetsTot10,
  optellenOnder10,
  dubbelen,
  kloptDeSom,
  ontbrekendGetal,
  drieGetallen,
  splitsenInDelen,
  eindtoetsTot10,
];
